/* Generated from data/showcase.json by tools/check_v2.py --write-js. Edit the JSON, not this file. */
window.PL_SHOWCASE = {
 "about": "Closing showcase: five GENERATED Ours outputs (a sixth, #17, is listed under \"excluded\" since R8) selected by the author from the supplemental gallery; not retrieved training data. Per REVISION_NOTES.md R5, each is shown at normal speed (1x) for its decisive transition (2.5-2.9 s) plus a short hold; source in/out (seconds), rate and hold below. Labels are phenomenon names grounded in inspected frames and source prompts. Evaluator scores/prose in the source manifest are provenance only and are not shown.",
 "source_archive_sha256": "96465b82e75b271394d126bceb189d17f0775c479ac03df17053d202db4a071c",
 "sequence": [
  {
   "gallery_number": 12,
   "id": "sc12",
   "src": "assets/showcase/Ours_Cosmos3-Nano_12.mp4",
   "sha256": "3be9f8e389f7049dc24f07c646368782114d7f210e18da01941a679c7c6a210d",
   "backbone": "Cosmos3-Nano",
   "label": "Contact and collision",
   "sentence": "The blocks topple in sequence.",
   "duration": 5.041667,
   "fps": "24/1",
   "width": 832,
   "height": 480,
   "benchmark_prompt_source": "Physics-IQ",
   "source_video_id": "trimmed-block-domino.mp4",
   "source_prompt": "A row of colorful wooden blocks lined up on a wooden table with a wooden stick attached to a black rotating platform. The platform rotates clockwise and the wooden stick hits the first block as it rotates. Static shot with no camera movement.",
   "provenance_status": "User-supplied curated generated example, not retrieved training data; model run/seed not independently verified.",
   "in": 2.5,
   "out": 5.02,
   "rate": 1.0,
   "display_seconds": 2.52,
   "segment_reason": "Stick approaches and hits the row; full cascade; final frame held.",
   "rate_label": "",
   "hold_seconds": 0.6
  },
  {
   "gallery_number": 14,
   "id": "sc14",
   "src": "assets/showcase/Ours_Cosmos3-Nano_14.mp4",
   "sha256": "446a85bf5282356a814daeed16bc37c9b0962b1c78203cc09f488089014169de",
   "backbone": "Cosmos3-Nano",
   "label": "Wetting and deformation",
   "sentence": "The paper settles and deforms in the liquid.",
   "duration": 5.041667,
   "fps": "24/1",
   "width": 832,
   "height": 480,
   "benchmark_prompt_source": "Physics-IQ",
   "source_video_id": "trimmed-napkin-soak.mp4",
   "source_prompt": "A grabber tool holds a piece of paper towel over a shallow dish of light blue liquid on a wooden table. The grabber releases the paper towel on the dish. Static shot with no camera movement.",
   "provenance_status": "User-supplied curated generated example, not retrieved training data; model run/seed not independently verified.",
   "in": 1.0,
   "out": 3.8,
   "rate": 1.0,
   "display_seconds": 2.8,
   "segment_reason": "Folded towel collapses into the liquid and settles, deformed.",
   "rate_label": "",
   "hold_seconds": 0.35
  },
  {
   "gallery_number": 15,
   "id": "sc15",
   "src": "assets/showcase/Ours_Cosmos3-Super_15.mp4",
   "sha256": "985bae5cc69237e90fcdbd8bf9dfc7f88fb2eb25948bb37b5023e4909c8493c0",
   "backbone": "Cosmos3-Super",
   "label": "Tearing under tension",
   "sentence": "The tear opens as the grips pull apart.",
   "duration": 5.041667,
   "fps": "24/1",
   "width": 832,
   "height": 480,
   "benchmark_prompt_source": "Physics-IQ",
   "source_video_id": "0043_perspective-left_trimmed-cut-paper.mp4",
   "source_prompt": "Two black and blue gripping tools are pulling a piece of green paper from its two corners, causing it to tear. Static shot with no camera movement.",
   "provenance_status": "User-supplied curated generated example, not retrieved training data; model run/seed not independently verified.",
   "in": 2.0,
   "out": 4.8,
   "rate": 1.0,
   "display_seconds": 2.8,
   "segment_reason": "Crease, tear opening, halves separating.",
   "rate_label": "",
   "hold_seconds": 0.35
  },
  {
   "gallery_number": 16,
   "id": "sc16",
   "src": "assets/showcase/Ours_Cosmos3-Super_16.mp4",
   "sha256": "173098bfa62c4edfc45facdb162e987269e4bfbcad4299d4d2beac201006047f",
   "backbone": "Cosmos3-Super",
   "label": "Motion and shadows",
   "sentence": "The shadow changes as the mug rotates.",
   "duration": 5.041667,
   "fps": "24/1",
   "width": 832,
   "height": 480,
   "benchmark_prompt_source": "Physics-IQ",
   "source_video_id": "0078_perspective-right_trimmed-light-on-mug.mp4",
   "source_prompt": "A yellow mug is placed on a rotating turntable that rotates clockwise illuminated by a spotlight casting a shadow on the wall behind it. Static shot with no camera movement.",
   "provenance_status": "User-supplied curated generated example, not retrieved training data; model run/seed not independently verified.",
   "in": 1.2,
   "out": 4.0,
   "rate": 1.0,
   "display_seconds": 2.8,
   "segment_reason": "Handle shadow on the right, hidden as the mug turns, then on the left.",
   "rate_label": "",
   "hold_seconds": 0.35
  },
  {
   "gallery_number": 18,
   "id": "sc18",
   "src": "assets/showcase/Ours_Wan2.1-14B_18.mp4",
   "sha256": "46f2d1328561e0ce0767f50c2b5794dab073e685a11d58635077b608a0efea76",
   "backbone": "Wan2.1-14B",
   "label": "Deformation under load",
   "sentence": "The pillow compresses beneath the weight.",
   "duration": 5.0625,
   "fps": "16/1",
   "width": 832,
   "height": 480,
   "benchmark_prompt_source": "Physics-IQ",
   "source_video_id": "trimmed-weight-on-pillow.mp4",
   "source_prompt": "A 30lb kettlebell and a green piece of paper are lowered onto two pillows. Static shot with no camera movement.",
   "provenance_status": "User-supplied curated generated example, not retrieved training data; model run/seed not independently verified.",
   "in": 0.3,
   "out": 3.0,
   "rate": 1.0,
   "display_seconds": 2.7,
   "segment_reason": "Kettlebell lowered onto the pillow; pillow compresses under the load.",
   "rate_label": "",
   "hold_seconds": 0.35
  }
 ],
 "slots": [
  {
   "id": "sc12",
   "start": 97.8,
   "clip_start": 97.95,
   "clip_end": 100.47
  },
  {
   "id": "sc14",
   "start": 101.07,
   "clip_start": 101.22,
   "clip_end": 104.02
  },
  {
   "id": "sc15",
   "start": 104.37,
   "clip_start": 104.52,
   "clip_end": 107.32
  },
  {
   "id": "sc16",
   "start": 107.67,
   "clip_start": 107.82,
   "clip_end": 110.62
  },
  {
   "id": "sc18",
   "start": 110.97,
   "clip_start": 111.12,
   "clip_end": 113.82
  }
 ],
 "excluded": [
  {
   "gallery_number": 17,
   "id": "sc17",
   "src": "assets/showcase/Ours_Wan2.1-14B_17.mp4",
   "sha256": "7fad58056e846419ae644602941233fae90de14f15ba93a9737cd90edf321d00",
   "backbone": "Wan2.1-14B",
   "label": "Optical magnification",
   "sentence": "Text appears enlarged through the lens.",
   "duration": 5.0625,
   "fps": "16/1",
   "width": 832,
   "height": 480,
   "benchmark_prompt_source": "PhyGenBench",
   "source_video_id": "video_0066.mp4",
   "source_prompt": "A magnifying glass is gradually moving closer to the pages of an open book, revealing the intricate details and textures of the printed text as it approaches.",
   "provenance_status": "User-supplied curated generated example, not retrieved training data; model run/seed not independently verified.",
   "in": 1.9,
   "out": 4.8,
   "rate": 1.0,
   "display_seconds": 2.9,
   "segment_reason": "Lens enters and covers the text; characters appear enlarged.",
   "rate_label": "",
   "hold_seconds": 0.35,
   "excluded_in": "R8",
   "exclusion_note": "Removed from the presentation at the author's request (R8). The source clip file is retained in assets/showcase/ and is not loaded by the page."
  }
 ]
};
